project:
  type: book
  output-dir: docs

book:
  title: "book"
  author:
    - Lars Schöbitz
    - Matthias Bannert
  sidebar:
    style: docked
    background: light
  navbar: 
    search: true
  repo-url: https://github.com/openwashdata/book/
  repo-actions: [edit]
  downloads: [pdf]
  date: today
  date-format: long 
  chapters:
    - index.qmd
    - learner-personas.qmd
    - wp0-infrastructure.qmd
    - wp1-mobilize.qmd
    - wp2-share.qmd
    - wp3-clean.qmd
    - wp4-communicate.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



