# Learner personas

Our proposal is not only open to all research disciplines, thematic areas, geographical locations, and levels of expertise with respect to data literacy, computational competencies, or statistics knowledge, but we encourage and rely on diversity. To illustrate they diversity we expect, we have designed four learner personas (Table 1). Writing learner personas for teaching programming is a concept established by [@wilson2019teaching] and is a crucial step in understanding the needs and expectations of the participants.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#| label: tbl-learners

readr::read_csv("https://raw.githubusercontent.com/openwashdata/website/main/pages/proposal/learner-personas.csv") |> 
      knitr::kable(caption = "Overview of learner personas designed for openwashdata community.") 
```

**Palesa** is leading a pit latrine emptying business with 20 employees and 6 vacuum trucks in Lusaka, Zambia. She has finished high school and did an apprenticeship in business administration. She is also a representative for the Sanitation Workers Association of Sub-Saharan Africa. She knows how to setup a data table using spreadsheet based software. She tracks all her business information using this software, but has never had any formal introduction into data organisation in spreadsheets. When asked to share to data, she shares the relevant worksheet by email. She is constantly approached by researchers, consultants, and public servants about sharing data on the amounts of types of faecal sludge removed from sanitation systems. While she is willing to share information, she is frustrated by and tired of follow up questions and the number of requests. She wants to learn how to give people access to her data at a central location, so that everyone can access the data from there. She is building a house for her family of five with the revenues of her business. She juggling many responsibilities and does not have any time to participate in formal training.

**Yua** is a Japanese PhD student in Computer Science at ETH Zurich. She is an active contributor to open source software packages and has a passiong for Open Science principles. She is proficient in half a dozen programming languages and uses R and Python for Data Science tasks. She has an R package for data visualisation on GitHub, which has received more than 500 stars. Her best friend works in the WASH sector and she has learned a fair bit about it. Her great experience and expertise in data cleaning enable her to decode data structures with minimal metadata. She wants use her technical skills to contribute to open communities and use her experience to support others in becoming more proficient in using computational tools. The openwashdata community provides the ideal starting point for her to do that. She also hopes to use the wealth of data that is opened by the community to advance her Computer Science PhD research on barriers to computational reproducibility. She is introverted and prefers to communicate with people online.

**Mandla** is in his final year of a Master of Science in Urban Planning at Makerere University in Kampala, Uganda. He is supporting Senior Researchers at the university in data collection for WASH related projects and is highly motivated to learn modern data science tools for his data analysis tasks. He did well in his high school math classes, and has watched some free online courses on using R for data analysis. He is struggling with file management and has recently lost three months' worth of data, as his hard drive was corrupted. He knows that there is a better way to analyse and manage data, but he hasn't found the right material and motivation that teaches him the tools that he needs. He wants to participate in 12-week course that teaches him the foundational knowledge and wants to apply the learned skills to support the openwashdata community in their mission to publish open data. He doesn't have money to buy a laptop. He uses the infrastructure at the university, but during the recent student strike at the university the computer lab was damaged and is currently closed.

**Asim** has been working at a research institute in Aachen, Germany for 25 years. He holds a PhD and is a group leader with a focus on solid waste management research. Throughout his career, he has supported more than 100 students and research assistants in their early career research stages. He has never written a line of code, but is highly proficient in using MS Excel. He has a particular fear to share data with other researchers or alongside journal publications, because he believes that others could judge his practices or may even use his data to write their own publications. He is very particular about workflows, file and data management. During the offboarding process of each employee, he has ensured that generated research data stored on a long-term archive server, following his guidelines for directory structure and documentation. He wants to share this data with the openwashcommunity under the condition that he and every researcher that was involved in creating the data gets appropriate credit for their work. He has three more years until retirement is reluctant to learn any new tools and feels very uncomfortable with anything outside his normal working environment. He needs someone to show him step by step how to share he research data with the community.
