# WP0: Infrastructure Design and Installation

:::{.callout-note}

## Goal: The Goal of WP0 is to prototype a technical foundation for the ORD toolchain at ETH in a a way that allows teaching and scientific collaboration to continue beyond the explore project's funding.

**RQ 0.1:** What are the costs and requirements for ORD tools to be hosted and maintained within the ETH domain?

**Activity 0.1:** Collaborate with ETH IT Services to establish Virtual Machines and RStudio Server (open source version) for 50 learners

**Activity 0.2:** Evaluate the advantages and disadvantages of three open source tools for communication (Slack, Discord, Matrix Protocol)

To facilitate communication in a variety of contexts such as online support for dataset submission, teaching or scholarly writing is of the most important tasks of the technical ecosystem of openwashdata. 
In order document our decision for the *matrix* network for secure, decentralized communication, let us understand first why a chat is such an important form of communication for our project.
Chat platforms allow to organize discussions very dynamically in rooms, channels or topics as well as peer to peer communication. 
Communication works well in async situations, similar to message boards and issue trackers.
At the same chats allow for dynamic live discussions in groups or peer-to-peer.  
The ability to present data as well as source code in visually appealing fashion is a strong advantage over, e.g., e-mail for our project. 

While the per user pricing models of software-as-a-service (SaaS) providers like Slack or Discord allow to use all of the above features without thinking of operating an own server, the underlying software is not open source nor do we have control over the data. 
Given the crucial role of a chat platform, especially when an openwashdata community has been established, these shortcomings of a SaaS solutions weigh heavy in our case. 
Fortunately, ETH Zurich operates a so-called homeserver for the *matrix* network.
This allows staff members and students to join internal as well as global chat rooms on the matrix network. 
In addition, users from other organizations' home servers can join chat spaces linked to the ETH upon invite. 
Using ETH matrix server we can even expose certain rooms publicly, so that they can be found on a global matrix channels catalog. 
Thanks to ETH' contribution to the matrix network we were able to choose a solution that fulfills all of our needs, enables us to connect to external collaborators, allows for control of all data and at the same time has virtually no operating costs for us. 
While per user costs are not a short term issue when the user base is relatively small, such costs can hurt our goal to establish a community when seed funding expries and potentially hundreds of users have joined. 


**Activity 0.3:** Compare hosting costs and technical overhead (maintenance) of RStudio Cloud by RStudio PBC with Virtual Machines hosted at ETH Zurich.
:::

<!--#  Text from proposal

During our upstream working package 0, we address costs and requirements for hosting a full fledged ORD process within the ETH domain. In the process, we will collaborate with ETH IT services to establish an open source backed ecosystem for a milestone of 50 learners. Infrastructure automation, e.g., through ansible automation platform is crucial to our approach: Scripted setups allow to reproduce our setup, disseminate our learnings and to foster ORD practices within ETH and beyond. Our work in WP0 is not limited to computing and version control infrastructure, we also plan to invest into communication tools that suit our approach of interactive collaboration in-person and online.

Based on our experience and previous work that lead to our submission, we intend to use open source software that is commonly applied throughout modern data science and statistics classes [@cetinkaya-rundel2018infrastructure], including: R and RStudio Server for programming; Quarto scientific and technical publishing system for authoring [@allaire2022quarto]; Git and GitHub for version control and collaboration; Matrix protocol for real-time communication ; Mailing list server for regular updates directly to email.

Together with ETH IT services we will not only evaluate the best options to self-host our current explore project, but also make sure our virtual infrastructure can be extended or migrated to other providers easily. The above ecosystem will be used for teaching, collaboration and community building beyond this project and contribute to the greater understanding of how open source software can be integrated into ETH infrastructure, teaching and learning. Given the heterogeneity of the WASH community, a non-propietary is crucial for global adaption of a technical framework.

-->

## Research Question 0.1

## Activity 0.1

## Activity 0.2

## Activity 0.3
